### ISSUE TITLE
Algoritmo Pseint sprint 1

### ISSUE THREAD

**Issue by LizethYomairaMontoyaGarcia** [MAKAIABootcamp/frontend-cohorte-4#10]
# Algoritmos Pseint
### estructura de carpetas 
![image](https://user-images.githubusercontent.com/125513835/222208621-797641a6-bb66-4a49-a2a5-f3e105b3793c.png)

###Resumen de paso a paso del desarrollo de Pseint, en este encontraran todos los archivos de las actividades asignadas.

**Comment by WhitneySt** [comment]
### Calificación
96%
