### ISSUE TITLE
Workshop 2 Paguina Web, sprint 1

### ISSUE THREAD

**Issue by LizethYomairaMontoyaGarcia** [MAKAIABootcamp/frontend-cohorte-4#11]
#Workshop Pokedex
### Estructuras de carpetas.
![image](https://user-images.githubusercontent.com/125513835/222247072-3bbbb3e3-9336-4d10-a8b2-9b25ab134b69.png)
### Resumen de paso a paso, se creo una paguina de Html y de estilos para pa la paguina de Pokedex.

###Vistas
## Estadisticas Wakatime 
![image](https://user-images.githubusercontent.com/125513835/222247875-a0ee0fad-8dfa-4f23-b595-ffa752b10f39.png)
[Estadisticas](https://wakatime.com/@3cca90b5-6d10-4257-85f2-9d66e444b5b6/projects/qhzhjvyenj?start=2023-02-23&end=2023-03-01)

**Comment by WhitneySt** [comment]
### Calificación 99%
