### ISSUE TITLE
Sprint 1 | Workshop 1

### ISSUE THREAD

**Issue by yesid10** [MAKAIABootcamp/frontend-cohorte-4#13]
# Algoritmos Pseint

[URL Repositorio](https://github.com/yesid10/Spirnt-1_Workshop1)

## Descripcion del desarrllo: 
Se instalo la herramienta pseint para empezar a implementar logica de programacion y desarrollaron ejercicios practicos para tener nociones y empezar a utilizar un lenguaje de programacion.

### Estructura de carpetas:
![image](https://user-images.githubusercontent.com/114708064/222262137-4ab7665c-5035-4644-baf3-5533b5f7325a.png)

### Paso a paso y desarrllo:
1. Se instalo pseint.
2. Empezamos a configurarlo para poder utilizarlo.
3. Se dio introduccion a pseint y a utilizar todas la herramientas previamente vistas.
4. Se empezo a dar solucion a los ejercicios propuestos.

**Comment by WhitneySt** [comment]
### Calificación 100%
