### ISSUE TITLE
Sprint 1 | Workshop 2

### ISSUE THREAD

**Issue by yesid10** [MAKAIABootcamp/frontend-cohorte-4#16]
# Pagina POKEDEX

## Descripcion del desarrollo:
Se implemento, todas las etiquetas vistas en clase, dandole buen uso a esas e intentado dejar de lado las etiquetas que pueden dar mala posicion a nuestra pagina en internet. De igual manera, para el desarrollo de esta pagina se implemento CSS para estilizar la misma y que sea mas amigable con el usuario.

## Estructura de carpetas: 
![image](https://user-images.githubusercontent.com/114708064/222265216-97d0c18f-800f-48e6-9c2c-f392ae5e2b5e.png)

### Index:
1. Se da la estructura de la pagina 
2. Utilizamos las etiquetas adecuadas para cada apartado: header, main, footer.
### CSS
1. Se puso los id y las clases necesarias a las etiquetas para despues llamarlas en css
2. Se estilizo header, footer, main.
3. Se dio a animacion al footer con el hover.

## Estadisticas Wakatime:
![image](https://user-images.githubusercontent.com/114708064/222266431-3a881a79-1b85-463d-ac5a-a90ae44f0c8a.png)

[Estadisticas](https://wakatime.com/@ea7be015-4527-4980-88b1-4124080a865c/projects/udlhbnmtej?start=2023-02-23&end=2023-03-01)

**Comment by WhitneySt** [comment]
### Calificación
91%
