### ISSUE TITLE
ALGORITMOS sprint 1 psIent 

### ISSUE THREAD

**Issue by AngieMorenoOrtega** [MAKAIABootcamp/frontend-cohorte-4#17]
#algoritmos
##	Descripcion del desarrollo:
en el ejercicio suma crear un espacio de texto mediante Escribir con el texto 'digite los números que quiere sumar'
a continuación la acción leer  junto con las variables (4) que son: numero_,numero_2,numero_3,numero_4
luego una función indicando la operación que en este caso es suma entonces se le coloca el signo (+) : resultado<-(numero_)+(numero_2)+(numero_3)+(numero_4)
por último, la acción escribir resultado, para mostrar un espacio de texto con el resultado de la función.
en el ejercicio de calcular el cuadrado, primero crear un cuadro de texto para ingresar el numero, luego la variable numero, y luego la operacion que es multiplicación de la variable por ella misma, por último la acción escribir resultado, para mostrar un espacio de texto con el resultado de la función.
en el ejercicio de calcular la edad coloque varias variables: dia, mes, año de nacimiento con su respectiva acción: leer; también día y mes actual ya que el año no será una variable sino parte de la función, también les coloque la accion leer;
luego la función que es una resta edad<-2023-ano_de_nacimiento
una condicional si con tres condiciones , ya que en caso de estar en un mes en el que aun no ha cumplido años (o) en el mismo mes de nacimiento pero (y) en un dia que aun no es el dia en que nacio entonces se le resta uno a la variable edad que es el resultado de la funcion anterior. por ultimo se escribe el resultado.
en el ejercicio calcular el precio de productos, primero defino las variables que segun el ejercicio son (5) productos, en la primera funcion para calcular el iva, se crea la variable (iva) la cual sera resultado de una multiplicacion por cien y division por 19
este resultado se escribe con el mensaje 'el porcentaje es:'
en la segunda funcion para calcular el el precio bruto se crea la variable (precio bruto) la cual sera resultado de una suma de las variables este resultado se escribe con el mensaje 'el precio bruto es:'
para realizar la ultima funcion se crea una variable (precio neto) la cual sera el resultado de la suma de la variable iva y precio bruto
este resultado se escribe con el mensaje 'el precio neto es:'
en el siguiente ejercicio se crean las variables modelo y marca y luego al escribir se modifica el orden de las variables
en el siguiente ejercicio se crean las variables alumnos y rubios, con su respectivo mensaje de texto para ingresarlos, luego se crea una funcion que haga la operacion rubios*100/alumnos y de como resultado la variable resultado que se escribira al final.
en el ejercicio 'rectangulo' se utilizan dos variables que son alto y ancho luego se hace una variable que de como resultado el perimetro, la funcion es una suma de las dos variables multiplicadas cada una por dos  y lo escriba, asimismo la segunda funcion es una multiplicacion y da como resultado la variable de resultado area, esta se escribe con un mensaje que diga  metros cuadrados mas el resultado.

**Comment by WhitneySt** [comment]
### Calificación
98%
