### ISSUE TITLE
Sprint 1 | Workshop 1 | PSeInt

### ISSUE THREAD

**Issue by LuisaLafaurie** [MAKAIABootcamp/frontend-cohorte-4#18]
# Workshop 1 - Sprint 1

## **Descripción del desarrollo:**
Ante cada problema y con ayuda de la práctica en clase, pude implementar la estrategia de identificar el problema a resolver y los datos que necesitaba para ejercutarlo, por lo que si había alguna fórmula matemática que no conocía, la consultaba por internet y/o preguntaba con otras personas y de esa manera pude desarrollarlos.

## **Estructura de archivos:**
![image](https://user-images.githubusercontent.com/125611741/222273272-094ac285-849b-4734-85e6-64058fd91021.png)

## **Resumen de paso y paso y desarrollo:**
1. Leer el ejercicio
2. Identificar los datos que piden
3. Identificar los comandos a usar
4. Realizar un orden lógico con los datos que se identificaron
5. Ejecutarlo y probarlo con F9 para verificar su correcta función

**Comment by WhitneySt** [comment]
### Calificación
100%
