### ISSUE TITLE
Sprint 1 | Workshop 2 | Pokédex

### ISSUE THREAD

**Issue by LuisaLafaurie** [MAKAIABootcamp/frontend-cohorte-4#19]
# Workshop 2 - Sprint 1

## **Descripción del desarrollo:**
Se usaron varias etiquetas aprendidas en clase y por medio del auto estudio que hicieron gestionar de mejor la menra la manera en que iba a maquetar la página web.

## **Estructura de carpetas:**
![image](https://user-images.githubusercontent.com/125611741/222276801-4dd49a7b-f76e-4544-b1e1-bc982eebd891.png)

## **Resumen de paso y paso y desarrollo:**
1. Estructurar las etiquetas base en los archivos html y css
2. Organizar la información en el orden que debe estar posicionado
3. Empezar a gestionar la estructura desde el menú incluyendo los estilos css en adelante
4. Al llegar a la información del pokemon, buscar información acerca de flexbox para una mejor visualización de la imagen y los datos
5. Agregar un plus a la portada
6. Realizar finalmente el footer que tomó mucho tiempo por intentar hacerlo en diferentes formas, y al haber logrado la base, implementar un plus a la galería de los pokemons

## **Estadísticas de WakaTime:**
![image](https://user-images.githubusercontent.com/125611741/222279913-a1de0e0e-76ca-41ae-b590-63da05d9686e.png)

**Comment by WhitneySt** [comment]
### Calificación 
99%
