### ISSUE TITLE
Algoritmo pseint Sprint 1

### ISSUE THREAD

**Issue by yesid10** [MAKAIABootcamp/frontend-cohorte-4#2]
# Algoritmos Pseint
### Estructuras de carpetas:
![image](https://user-images.githubusercontent.com/114708064/221999532-26a09991-106d-424c-a115-f297e49ef908.png)
## Estadisticas Wakatime:
![image](https://user-images.githubusercontent.com/114708064/222000265-f48939f1-4c28-406e-97a9-c2205ca8a3b1.png)

[Estadisticas](https://wakatime.com/@ea7be015-4527-4980-88b1-4124080a865c/projects/udlhbnmtej?start=2023-02-22&end=2023-02-28)

**Comment by WhitneySt** [comment]
### Calificación 
100%
