### ISSUE TITLE
Workshop2 Sprint!

### ISSUE THREAD

**Issue by dianaleja** [MAKAIABootcamp/frontend-cohorte-4#20]
# PaginaPokemon
### Estructura de carpetas
![image](https://user-images.githubusercontent.com/126523119/222279791-da314a2d-d6bf-4de6-849b-2dbb7c9c9a79.png)
### Vistas
![image](https://user-images.githubusercontent.com/126523119/223282574-f08cd074-7d55-4e37-b06d-cb04154ecda4.png)

### Estadisticas wakatime
![image](https://user-images.githubusercontent.com/126523119/222281897-e3173d83-84db-4285-a2b6-95ac30678ad3.png)

### Estadisticas wakatime 
[Estadistica ](https://wakatime.com/@6e14c978-6753-49e9-9606-6fb30ec9e683/projects/zbqfyuonup?start=2023-02-28&end=2023-03-06)

**Comment by WhitneySt** [comment]
### Calificación
100%
