### ISSUE TITLE
Sprint 1 | Workshop 1 | Pokedex

### ISSUE THREAD

**Issue by NeisRosado** [MAKAIABootcamp/frontend-cohorte-4#21]
# Página Web Estática
### Descripción del Desarrollo 
En este Workshop se construyó una página web estática usando HTML y CSS  

### Estructura de Carpeta

![vscpokedex](https://user-images.githubusercontent.com/125513445/222279817-05b564ec-7493-45b1-ac27-cd6034b3e4f6.PNG)

### Resumen Paso a Paso 

El ejercicio se realizó con la siguiente estructura:
- Header - Main - Footer - Mouse over

En primer lugar, se realizó el maquetado de página en Html y se seleccionaron las imágenes, 
luego, se generaron los estilos en Css, verificando en el navegador cada cambio aplicado. 

### Vista Deskopt 

![screen-pokedex (2)](https://user-images.githubusercontent.com/125513445/222288400-efca6bc8-decc-4b72-96bb-c8fd5c7d73bd.gif)

![vistapokedek](https://user-images.githubusercontent.com/125513445/222283381-165a1a2d-95f9-4dd6-9dab-6382fc570ebc.PNG)

### WakaTime

![wakafile1](https://user-images.githubusercontent.com/125513445/222287327-37511174-c7ae-48f0-ac75-3050c362854b.PNG)

![wakatotal](https://user-images.githubusercontent.com/125513445/222287179-6667548a-9acf-4a6e-8160-727ae47c77c1.PNG)

**Comment by WhitneySt** [comment]
### Calificación
99%
