### ISSUE TITLE
Sprint 1 Workshop 1 PSeInt

### ISSUE THREAD

**Issue by 3AnaMaria** [MAKAIABootcamp/frontend-cohorte-4#23]
# Algoritmos Pseint
### Estructuras de carpetas:
![image](https://user-images.githubusercontent.com/125514163/222290495-f74c26c8-d89e-4ba5-8fe8-c27481584f96.png)

[Estadisticas](https://wakatime.com/@ea7be015-4527-4980-88b1-4124080a865c/projects/udlhbnmtej?start=2023-02-22&end=2023-02-28)

**Comment by WhitneySt** [comment]
### Calificación
100%
