### ISSUE TITLE
ACTIVIDADES HTML Y CSS -PABLO REVELO

### ISSUE THREAD

**Issue by PABLORVLO** [MAKAIABootcamp/frontend-cohorte-4#25]
#SPRINT1-HTML-CSS
<img width="106" alt="visual captura" src="https://user-images.githubusercontent.com/120429005/222294213-76521fe5-3531-4369-9525-346c8c0fb6ec.png">
CAPTURA DE WAKATIME
![image](https://user-images.githubusercontent.com/120429005/222294427-03b48fc2-2bb0-4001-907a-baa6081c1edb.png)
#Link del repositorio
https://github.com/PABLORVLO/Sprint1-html-css

**Comment by WhitneySt** [comment]
### Calificación
99%
