### ISSUE TITLE
sprint 1 (whorkshop 1)

### ISSUE THREAD

**Issue by vladie777** [MAKAIABootcamp/frontend-cohorte-4#27]
# Algoritmos Pseint.
nombre: Diego luis meriño caceres
### Estructuras de carpetas:
![Captura](https://user-images.githubusercontent.com/126520472/222294956-0bc1f653-e7ed-4691-8c64-285945c59545.JPG)

**Comment by WhitneySt** [comment]
### Calificación
100%
