### ISSUE TITLE
Algoritmos PseInt WorkShop 1

### ISSUE THREAD

**Issue by linavaquero** [MAKAIABootcamp/frontend-cohorte-4#28]
# Ejercicios PseInt
## Descripción del desarrollo
Se crean algoritmos en PseInt para desarrollar lógica de programación de los siguientes ejercicios:

1. Área de un triangulo
2. Artículos del mercado
3. Calculando perímetro y área de un rectángulo
4. calculo de cuadrado
5. calculo de edades
6. Modelo marca auto
7. Números enteros
8. Porcentaje

### Estructuras de carpetas:
![image](https://user-images.githubusercontent.com/125513574/222296307-fd69990b-d415-41a0-b766-edc131cb0d2c.png)
### Resumen de paso a paso y desarrollo
Se creo el proyecto en la herramienta PseInt se leen las variables se realizan los cálculos necesarios, se muestran los resultados en consola y se cargan los archivos al repositorio
### Vistas
![image](https://user-images.githubusercontent.com/125513574/222297396-767f57b8-c8a3-420a-8906-9f06ae631f98.png)

**Comment by WhitneySt** [comment]
### Calificación
100%
