### ISSUE TITLE
sprint 1 (whorkshop 2)

### ISSUE THREAD

**Issue by vladie777** [MAKAIABootcamp/frontend-cohorte-4#29]
# Pagina estata POKEDEX
nombre: Diego Luis Meriño Caceres.
## Descripcion del desarrollo.
Crear un sitio web describiendo un pokemon de forma estatica y sin dirigirnos a otros sitios use etiquetas como header,main y footer las cuales los requisitos para este sitio web
### Estructuras de carpetas:
![Captura](https://user-images.githubusercontent.com/126520472/222296274-3874c0d7-3d2e-44db-83e4-889580c7aad1.JPG)
### Resumen de paso a paso y desarrollo.
-crear las estructura HTML.
-vincular el archivo CSS.
-crear la etiqueta head para agregar las imagenes de la pokebola y la etiqueta h1 para escribir pokedex.
-luego entro a google y busco la foto de los pokemones que necesito.
-busco en google fonts un tipo de letra que sea de mi agrado y lo copio en el css.
-luego de forma adicional abro photoshop y al fondo de las imagenes de los pokemones las cambio dependiendo del color del fondo de mi proyecto.
-en mi CSS organizo todo poniendo los colores de fondo y los tipos de letras entre otras.
-en el footer aplique el mouse over con una transicion en negro y agrandamiento de imagen.
## Estadisticas Wakatime:
me paso algo malo configure mal el wakatime y apenas inicio a funcionar hoy y estoy triste por eso 
![Captura](https://user-images.githubusercontent.com/126520472/222297727-0cc319f8-ba6c-4cbe-a7bc-437c55983077.JPG)

**Comment by WhitneySt** [comment]
### Calificación
98%
