### ISSUE TITLE
Algoritmo PSeint | Sprint #1 - Workshop #1

### ISSUE THREAD

**Issue by J-Ciro** [MAKAIABootcamp/frontend-cohorte-4#3]
# Algoritmos | Pseint Sprint 1 - Workshop 1
## Descripción de Desarrollo
Ejercicios Básicos de Programacion para comprender el concepto básico de Algoritmos y Logica de Programacion con ejercicio como:

- Area y Perímetro rectángulo
- Suma de Enteros
- Area de un triangulo

### Estructura de carpetas 
![image](https://user-images.githubusercontent.com/37349818/222002592-5969bca4-b426-43e3-99db-91e60ca64b71.png)

### Resumen del Desarrollo
Se aplicaron y se utilizaron las metodologías vistas en clase para poder solucionar de manera correcta los ejercicios.

**Comment by WhitneySt** [comment]
### Calificación
100%
