### ISSUE TITLE
Sprint 1 | Workshop 1 | Pokedex 

### ISSUE THREAD

**Issue by valentinasj** [MAKAIABootcamp/frontend-cohorte-4#30]
# pokedex
### Estructuras de carpetas.
![image](https://user-images.githubusercontent.com/125513622/222302565-1a815480-2999-41b8-8f4b-949f9e3bef46.png)
## estadísticas wacatime
![image](https://user-images.githubusercontent.com/125513622/222302761-20ccc38f-1373-4b98-90fa-9199344c755b.png)

**Comment by WhitneySt** [comment]
### Calificación
92%
