### ISSUE TITLE
WorkShop 2 Pokedex

### ISSUE THREAD

**Issue by linavaquero** [MAKAIABootcamp/frontend-cohorte-4#31]
# workshop 2 pagina web Pokedex
## Descripción del desarrollo
Es pagina web estática del Pokémon Pikachu con HTML5 y CSS3  
### Estructuras de carpetas
![image](https://user-images.githubusercontent.com/125513574/222304062-383714ff-2092-413c-aeac-3d9ff1baa8cb.png)
### Resumen del paso a paso y desarrollo

- Sea crea el proyecto en visual studio code

- Se crea la estructura de carpeta el archivo HTML con su estructura

- Se descargan las imágenes y se guardan en la carpeta img

- Se agregan al archivo HTML junto con la información del Pokémon escogido 

- Luego se crea el archivo CSS y se anexan los estilos correspondientes 

### Vistas
![image](https://user-images.githubusercontent.com/125513574/222304415-42e3484b-88f8-4b28-9fb5-fd272fd964c2.png)

## Estadísticas Wakatime
![image](https://user-images.githubusercontent.com/125513574/222304862-677741fb-1306-4e5c-90a8-4ffd3b4ce008.png)
![image](https://user-images.githubusercontent.com/125513574/222304935-c7c7130d-2f6c-49ae-8e66-9e4b860a4894.png)

**Comment by WhitneySt** [comment]
### Calificación
99%
