### ISSUE TITLE
Workshop 1, ejercicios Pseint - Yeraldin Montaño Monge

### ISSUE THREAD

**Issue by yeral-93** [MAKAIABootcamp/frontend-cohorte-4#33]
# Workshop 1 Pseint - Sprint 1
## Descripcion del desarrollo
Ejercicios Pseint de algoritmos, workshop 1, sprint 1.
### Estructuras de carpeta
<img width="581" alt="image" src="https://user-images.githubusercontent.com/116326313/222308506-39beb6a9-90a4-443f-b57b-c9a40d4ff2e2.png">

### Resumen del paso a paso y desarrollo:
Se realiza cada ejercicio pensando en la lógica y paso paso que se debe seguir.
### Vistas:
<img width="303" alt="image" src="https://user-images.githubusercontent.com/116326313/222308989-7295e728-e575-4e1f-943d-8b9f41a22853.png">
<img width="309" alt="image" src="https://user-images.githubusercontent.com/116326313/222309056-2b4bd224-ac5a-452f-8af6-b1581d1124f7.png">
<img width="680" alt="image" src="https://user-images.githubusercontent.com/116326313/222309131-ef954da4-f110-4fb4-8fcb-eb491a8714a1.png">
<img width="387" alt="image" src="https://user-images.githubusercontent.com/116326313/222309199-fcadaa13-e631-47f5-8cc8-79e6e712f164.png">
<img width="574" alt="image" src="https://user-images.githubusercontent.com/116326313/222309261-52a63d2d-23c7-4058-a025-83f48fd622c5.png">
<img width="523" alt="image" src="https://user-images.githubusercontent.com/116326313/222309340-393bf8a4-7661-43b7-95fd-08d3974e9fd2.png">
<img width="371" alt="image" src="https://user-images.githubusercontent.com/116326313/222309403-be1265e7-0a05-4f9b-8555-f32cfce877cc.png">
<img width="376" alt="image" src="https://user-images.githubusercontent.com/116326313/222309526-9e9fee67-6be5-41b4-a799-a639a4a8b08f.png">

**Comment by WhitneySt** [comment]
### Calificación
100%
