### ISSUE TITLE
Workshop 2, Pokédex - sprint 1 - Yeraldin Montaño Monge 

### ISSUE THREAD

**Issue by yeral-93** [MAKAIABootcamp/frontend-cohorte-4#34]
# Workshop 2 Pokedex- Sprint 1
## Descripcion del desarrollo
Pagína estatica usando html y css.
### Estructuras de carpeta
<img width="197" alt="image" src="https://user-images.githubusercontent.com/116326313/222312340-31c5c919-04c6-48ae-b9b5-a666c487d77d.png">

###  Resumen del paso a paso y desarrollo
Se abre un archivo index.html y otro style.css, en el index html se pone la estructura, agregó una imagen para el nav y una tag h2 para escribir un encabezado, después en el main agrego una tag h2 para poner nombre de pokemon, agrego otra tag figure y img para insertar la imagen de mi pokemón principal, después agrego una tabla con los datos del pokemón y por último en la sección del footer, agrego otra tag h2 para hacer referencia en lo que quiero y agrego las tags figure y img para insertar las otras 4 imágenes de los otros Pokémon. 

Después se le da estilo con css y sus diferentes propiedades, ej: para poner color al nav, se utiliza la propiedad background, para dar tamaño al texto, font-size. 
 
### Vistas
<img width="914" alt="image" src="https://user-images.githubusercontent.com/116326313/222312929-3775c030-c36a-4572-ae1a-c842826fe98c.png">

## Estadísticas wakatime
<img width="747" alt="image" src="https://user-images.githubusercontent.com/116326313/222313459-e342d6f8-1583-4574-a991-384546f98574.png">
<img width="744" alt="image" src="https://user-images.githubusercontent.com/116326313/222313184-d8789222-51e9-4f5a-9f23-a31e12cdb18d.png">
<img width="690" alt="image" src="https://user-images.githubusercontent.com/116326313/222313264-cc320e72-0c2f-4633-ac59-8b639639eaaf.png">

## [Estadistica wakatime](https://wakatime.com/@a30f14d9-f3ff-47f0-acfa-e2462c5e1761/projects/tgnpfzplyc?start=2023-02-23&end=2023-03-01)

**Comment by WhitneySt** [comment]
### Calificación
100%
