### ISSUE TITLE
Workshop 2 - Pokedéx

### ISSUE THREAD

**Issue by SantiagoDeAures** [MAKAIABootcamp/frontend-cohorte-4#36]
#Pokedéx
### Estructura de carpetas:
![image](https://user-images.githubusercontent.com/82245815/222320515-dd2adfbe-a224-4926-b0e0-e18a2c335f5c.png)

###Vistas:
![image](https://user-images.githubusercontent.com/82245815/222320710-a5c18cb1-4122-4a66-b944-5753cbaa5749.png)

## Estadisticas Wakatime:
![image](https://user-images.githubusercontent.com/82245815/222321172-a19e6f1c-71f9-4c2c-9cc7-22a8017485cb.png)

**Comment by WhitneySt** [comment]
### Calificación
100%
