### ISSUE TITLE
Workshop 1 y 2

### ISSUE THREAD

**Issue by AndresParra11** [MAKAIABootcamp/frontend-cohorte-4#37]
Hola,

Dejo el link de los dos repositorios del Workshop 1 y 2.

# Workshop 1: Algoritmos PseInt

## Descripción del desarrollo:

Se realizan diferentes ejercicios de lógica de programación usando la herramienta  PSeInt.

### Estructura de carpetas:

![image](https://raw.githubusercontent.com/AndresParra11/Workshop-1-PSeInt/main/Estructura%20de%20carpetas.JPG)

### Resumen de paso a paso y desarrollo:

- Lectura de cada uno de los ejercicios.
- Identificar las variables que se necesitan.
- Identificar los cálculos, ciclos, o funciones que se necesitan.
- Comenzar a diseñar el algoritmo.
- Ir probando el algoritmo línea a línea, que haga lo que queremos que haga.
- Finalizar el algoritmo.
- Probar que funcione.
- Celebrar.

# Workshop 2: HTML y CSS

## Descripcion del desarrollo:

El workshop 2 se compone de un archivo HTML donde se realiza toda la estructura (esqueleto) de la página web y un archivo CSS donde se le aplican todos los estilos necesarios para lograr la página estática solicitada. También se usan diferentes imágenes que se añaden mediante el documento index.html.

También se hace uso de un archivo CSS llamado reset.css, este me permite realizar el borrado de los estilos que vienen por defecto en los navegadores y partir desde cero. 

### Estructuras de carpetas:

![image](https://raw.githubusercontent.com/AndresParra11/Workshop-2-HTML-CSS/main/Screenshots/Estructuraci%C3%B3n%20de%20carpetas.JPG)

### Resumen de paso a paso y desarrollo:

- Identificación de información necesaria en la página web según el requerimiento del workshop.
- Diseñar el HTML con la estructuración requerida e identificada anteriormente, usando las etiquetas necesarias y correspondientes tratando de mantener buenas prácticas de programación.
- Aplicar el archivo reset.css para borrar todos los estilos que vienen por defecto en el navegador.
- Comenzar a diseñar el archivo de style.css, ha media que se va avanzando en la estructura se van añadiendo clases y ids necesarios para la estilización que requerimos. En este paso también se debe tener en cuenta que requerimos el uso de la pseudo clase :hover. 
- Realizar un proceso de mejora continúa donde corrijamos posibles errores que veamos y/o mejoramiento del estilo hasta llegar a un producto a gusto y que cumpla con los requerimientos.
- Pedir opinión a diferentes personas para ver como les parece el diseño y que me recomendarían. En el caso real, sería reunión con el cliente y ver el nivel de satisfacción que tiene.

Se siguieron las indicaciones de lo que debía tener en cuenta el header, body y footer de la página. Además se cumplió con la exigencia de algunos elementos del footer tuvieran la pseudo clase :hover.

### Vistas:

![image](https://raw.githubusercontent.com/AndresParra11/Workshop-2-HTML-CSS/main/Screenshots/Vista1.JPG)

![image](https://raw.githubusercontent.com/AndresParra11/Workshop-2-HTML-CSS/main/Screenshots/Vista2.jpg)

## Estadisticas Wakatime:

![image](https://raw.githubusercontent.com/AndresParra11/Workshop-2-HTML-CSS/main/Screenshots/Wakatime1.JPG)

[Estadisticas](https://wakatime.com/projects/Workshop%202%20-%20HTML%20y%20CSS)

Quedo atento a los comentarios, gracias!

**Comment by WhitneySt** [comment]
### Ejercicios de algoritmo
100%
### Pokedex
100%
