### ISSUE TITLE
Pokedex

### ISSUE THREAD

**Issue by LuisaUrrego** [MAKAIABootcamp/frontend-cohorte-4#38]
#  workshop 2: Pokemon
### Estructura de carpetas 
![image](https://user-images.githubusercontent.com/126603617/222317636-2d1da396-dfa6-4135-aa32-ad02cf3957ab.png)
### Resumen del paso a paso 
Primero cree una carpeta donde voy a almacenar todos mis archivos. Luego creo todos los archivos y empiezo a crear la estructura básica de mi index.html, seguido a esto empiezo a estructurar la página con las etiquetas para dividir todos sus elementos, creo las clases, las tablas, y descargo las imágenes que voy a utilizar. Continúo con el diseño en el style.css y empiezo a darle más forma al workshop, pongo la imagen, el texto y el color en el header, continuo con el main posicionando la imagen y las dos tablas que cree. Seguido a esto el footer, le doy color, tamaño, posiciono las cuatro imágenes y el texto. Por último realizo la función hover de modo que cuando el mouse se posicione sobre alguna de estas  cuatro figuras la imagen sea oscura o en mi caso que su tamaño aumente.
### Vistas
 ![image](https://user-images.githubusercontent.com/126603617/222320275-cc5f95e4-6cf0-455e-8a2b-992a95f261a1.png)
## Estadísticas wakatime
![image](https://user-images.githubusercontent.com/126603617/222321113-c82a5606-3d78-404f-93c9-159caab4de1d.png)
[Estadísticas wakatime ](https://wakatime.com/@65256321-d702-489d-83a7-88d491774b0c/projects/dfdlydokso?start=2023-02-23&end=2023-03-01)

**Comment by WhitneySt** [comment]
### Calificación
99%
