### ISSUE TITLE
Workshop1 Pseint - José_Sanmiguel

### ISSUE THREAD

**Issue by JJpepe12** [MAKAIABootcamp/frontend-cohorte-4#39]
# Workshop 1 Pseint
## Descripción del desarrollo.
Ejercicios Pseint de algoritmos, workshop 1, sprint 1.

### Estructuras de carpetas:
![image](https://user-images.githubusercontent.com/125513568/222328076-d3f1c0c2-de92-40ee-aa20-8470fb50e715.png)

### Resumen de paso a paso y desarrollo.
1. Realicé cada ejercicio según los conceptos aprendidos en la clase de lógica (sesión 2)
2. Lectura de cada ejercicio para identificar las variables y procesos adecuados
3. Diseño del algoritmo.
4. Clic en botón de ejecutar para probar el algoritmo
5. Ajustar los errores o mensajes de cada algoritmo
6. Guardar y salvar cada archivo

### Vistas: desktop

![image](https://user-images.githubusercontent.com/125513568/222329211-3d02d7d6-8cc8-4d68-b81f-85f6712f3292.png)

![image](https://user-images.githubusercontent.com/125513568/222329284-0c4ee4f1-90e1-4287-be2e-5ecae1d5ea57.png)

![image](https://user-images.githubusercontent.com/125513568/222329340-898f0e77-7b49-471f-bedd-d33a13c441b9.png)

![image](https://user-images.githubusercontent.com/125513568/222329402-bbfe0ed3-40be-41a2-8c14-c4c2b509404c.png)

![image](https://user-images.githubusercontent.com/125513568/222329437-2c2e8c20-c432-4a23-8de6-a789d2ff22df.png)

**Comment by WhitneySt** [comment]
### Calificación
99%
