### ISSUE TITLE
Página Web Estática | PokeDex Sprint #1 - Workshop #2

### ISSUE THREAD

**Issue by J-Ciro** [MAKAIABootcamp/frontend-cohorte-4#4]
# Página Web Estática | PokeDex Sprint 1 - Workshop 2
## Descripción de Desarrollo
Desarrolla página web estática usando HTML y CSS que cumpla con la siguiente estructura dada:
![image](https://user-images.githubusercontent.com/37349818/222006789-1ce42327-528f-45a2-ab3d-d85c6212362d.png)

### Estructura de carpetas
 La estructuración cuenta con un archivo ```index.html```, un archivo ```style.css``` y una carpeta ```imgs``` la cual contiene alguna de las imágenes usadas en el sitio como el Logo del sitio y el símbolo del tipo de Pokémon.

![image](https://user-images.githubusercontent.com/37349818/222006669-2bc6b99f-8638-4ff8-aa65-1bf1076f157d.png)

### Resumen del Desarrollo
El proyecto tuvo en cuenta los requerimientos dados para el desarrollo correcto del sitio web, contando con una correcta estructuración y utilización de :hover para el efecto del mouse cuando este pase por los Pokemons del footer.

- Para realizar el sitio se tomó la imagen dada tomando en cuenta las proporcione, ubicación y estructuración del sitio web para ser lo más precisó posible.

![image](https://user-images.githubusercontent.com/37349818/222007527-7bd47cf0-1a70-4545-9550-724aee0708ff.png)

- Se tomo en cuenta además la separación de cada elemento como lo seria ```header``` , ```main```, ```footer``` para poder cumplir con los requerimientos dados.

![image](https://user-images.githubusercontent.com/37349818/222008002-6d5ee2e6-be17-45c5-aded-61744d37a687.png)

- Para las imágenes de los Pokémon se utilizó el sitio web [Pokemondb](https://pokemondb.net/sprites) el cual nos permite utilizar o buscar todos los Pokémon que deseemos usar en nuestro sitio/proyecto.

![image](https://user-images.githubusercontent.com/37349818/222009045-1bc4795f-51fd-4498-938d-f158ed984ca0.png)

### Vistas: Desktop y Effecto Hover
![Grabación-2023-02-28-185525](https://user-images.githubusercontent.com/37349818/222010149-22ee1e7b-fb51-48f8-a249-a83fb48b3f39.gif)

## Estadisticas Wakatime:

![image](https://user-images.githubusercontent.com/37349818/222006519-ff061fc9-a7f2-4b08-9fbe-862595c6d8ea.png)

**Comment by WhitneySt** [comment]
### Calificación
100%
