### ISSUE TITLE
Sprint 1 Workshop 2 Pokédex

### ISSUE THREAD

**Issue by 3AnaMaria** [MAKAIABootcamp/frontend-cohorte-4#40]
# Algoritmos Pokedex
## Descripcion del desarrollo.
replica de la actividad realizada.
### Estructuras de carpetas:
![image](https://user-images.githubusercontent.com/125514163/222332109-0becf40b-109d-4a7e-90ee-0cf36dfba430.png)
## Estadisticas Wakatime:
[![image](https://user-images.githubusercontent.com/114708064/222000265-f48939f1-4c28-406e-97a9-c2205ca8a3b1.png)](https://wakatime.com/@6589ba54-4e9d-4b0c-a516-dc614e2ba8e4/projects/eoghtncads?start=2023-02-23&end=2023-03-01)

[Estadisticas]![image](https://user-images.githubusercontent.com/125514163/222332376-ef64dd8d-1109-4556-b3ac-fae6e7b7564b.png)
![image](https://user-images.githubusercontent.com/125514163/222332471-1116ab93-2d75-4940-bbc7-203e4ea52096.png)

**Comment by WhitneySt** [comment]
### Calificación
95%
