### ISSUE TITLE
Sprint2_paginaWeb_Pokemon

### ISSUE THREAD

**Issue by ElisabethOspinaG** [MAKAIABootcamp/frontend-cohorte-4#41]
**Estructura**
![image](https://user-images.githubusercontent.com/70925643/222331055-ffb7059a-ae99-417c-a7c2-a11f34aa3f4a.png)
**Proceso de desarrollo**
1. se creo la carpeta del ejercicio
2. se creo el archivo indexPokemon.html para desarrollar todo el codigo. utilicé las etiquetas más importantes como: 

- Header: Dentro del header coloqué el nombre y la pokebola
- Main: dentro del main creé dos div, uno para mostrar el nombre del pokemon principal y la imagen; y el segundo div para los detalles del poquemon. 
- Finalmente en el footer puse otros poquemones con sus imagenes
- 
3. Creé el archivo stylesPokemon.css para los estilos. Utilizé principalmente:
- Display flex: para centrar y alinear elementos
- Margin y paddings: para separar unos elementos de otros
- Background color: para asignar colores a los elementos
- Hover: para cambiar los estilos cuando el mouse esté sobre los elementos.

4. Creé la carpeta de imágenes para almacenar todos los pokemones que va a tener la página
5. Creé el repositorio y subí los ejercicios al github

**Pagina web**
![image](https://user-images.githubusercontent.com/70925643/222332919-dbdf0691-798d-47eb-ac44-57db72dea1f9.png)

**Wakatime:**
![image](https://user-images.githubusercontent.com/70925643/222330828-7ea53ccd-0e2c-4707-b5d3-cc08554d6b46.png)

[Repositorio](https://github.com/ElisabethOspinaG/MAKAIA/tree/main/SPRINT2_PaginaWeb_Pokemon)

**Comment by WhitneySt** [comment]
### Calificación
99%
