### ISSUE TITLE
Workshop2 Pokedex - José_Sanmiguel 

### ISSUE THREAD

**Issue by JJpepe12** [MAKAIABootcamp/frontend-cohorte-4#42]
# Workshop 2: Pokedex
## Descripción del desarrollo.
El workshop 2 contiene un index (HTML) con los elementos de la página web y un archivo CSS que aplica los estilos necesarios. Como resultado se obtiene una página estática que simula una Pokedez. También contiene un archivo de imagen para el logo usado en el header

### Estructuras de carpetas:
![image](https://user-images.githubusercontent.com/125513568/222330089-1655a679-7631-46a0-b6bb-4f1be6fc3021.png)

### Resumen de paso a paso y desarrollo.

1. En el index de HTML construí la estructura con la información presentada en el ejercicio, usando las etiquetas necesarias
2. Creé y vinculé un archivo style.css para dar estilo a los elementos del index
3. En index añadé las imágenes y tablas requeridas para mostrar la información, y las clases para estilizar en css. 
4. Por medio de Live server y probando la interfaz hice los ajustes necesarios, hasta llegar a la página estática deseada. 
5. Consulté en tutoriales las dudas que tuve al momento de corregir errores
6. Añadí la clase :hover en el footer.

### Vistas: Desktop
![image](https://user-images.githubusercontent.com/125513568/222330253-f9721bee-c233-4f94-9c99-4cd257d5d957.png)

## Estadisticas Wakatime:
![image](https://user-images.githubusercontent.com/125513568/222333727-cd292fe1-99f8-4f3e-9fab-6cfdaef77cb2.png)

[Estadisticas](https://wakatime.com/@dd0bf59f-035a-424c-817f-b4dab2230aad/projects/ksrrzbhnkf?start=2023-02-23&end=2023-03-01)

**Comment by WhitneySt** [comment]
### Calificación 
96%
