### ISSUE TITLE
Sprint 1 - Ejercicios logica psint

### ISSUE THREAD

**Issue by ElisabethOspinaG** [MAKAIABootcamp/frontend-cohorte-4#44]
**Proceso**
Se descargó la aplicación psint, y se desarrollaron cada uno de los ejercicios como se explicó en clase. utilizando como material de apoyo los conceptos aprendidos y los documentos de la plataforma.

**Estructura**
Todos los ejercicios se desarrollaron en el mismo archivo
![image](https://user-images.githubusercontent.com/70925643/222334109-4c7a0a47-b91c-4262-9100-2ba018f7998a.png)

**Wakatime**
![image](https://user-images.githubusercontent.com/70925643/222333752-27f90661-6260-431e-bc3c-5a6693ec6f2e.png)

Nota: Para el desarrollo de esta actividad tuve que hacerlo en otro computador por lo que no tenía wakatime configurado.

[Repositorio](https://github.com/ElisabethOspinaG/MAKAIA/tree/main/SPRINT1_Psint)

**Comment by WhitneySt** [comment]
### Calificación
98%
