### ISSUE TITLE
pokemon

### ISSUE THREAD

**Issue by vickmery** [MAKAIABootcamp/frontend-cohorte-4#46]
# pagina pokemon 
### estructura de carpetas 
![image](https://user-images.githubusercontent.com/125513818/222334908-fabd9378-d30e-4908-beed-5afe8a082f88.png)
### Resumen del paso a paso
primer lugar cree los archivos donde almaceno todo el codigo para la pagina de pokemon. Despues cree la estructura basica del Html y le adicione los selctores , las divisiones y las clases. Seguido de esto empece a darle diseño con Style.Css, diseñe las tablas, agregue color, cambie el tamaño de las imagenes, agregue el logo en el header; luego agregue la imagen del pokemon central , le puse sus respectivas medidas, lo posicione en el lugar indicado. finalmente diseñe el foother agregandole las otras imagenes posicionadolas agregando el texto, finalemnte agregue el hover para que la imagen cambie de color, lo logre con el efecto mouse cover.
### vistas
![image](https://user-images.githubusercontent.com/125513818/222335309-bd403e68-d4e7-4818-9e63-6e4cffbf1117.png)
## estadisticas wakatime
![image](https://user-images.githubusercontent.com/125513818/222335583-eb7dc5dc-082f-4ce5-ad57-b07ade9f5e83.png)

**Comment by WhitneySt** [comment]
### Calificación
96%
