### ISSUE TITLE
proyecto pokemon sprint 1 

### ISSUE THREAD

**Issue by AngieMorenoOrtega** [MAKAIABootcamp/frontend-cohorte-4#47]
# workShop_1_Pokemon-angiemoreno
## estructura de las carpetas
![image](https://user-images.githubusercontent.com/126519881/222510781-b9707d1f-33d2-47d8-8707-591dc6a00dcc.png)
##vistas
![image](https://user-images.githubusercontent.com/126519881/222511354-3006efcf-56a1-4298-9dcf-5c431e2a8e1c.png)
##proceso
en primer lugar cree un documento html con el nombre index
luego inicié el documento con la etiqueta !DOCTYPE html y html y la etiqueta de cierre html.
asimismo asigne el lenguaje con una etiqueta lang dentro de esta ultima
además agregué estructura mediante metadatos del documento las etiquetas head y meta   y le asigné un título a la página.
cree una carpeta con un archivo css, y luego enlace este archivo con el html mediante un link en la seccion head
después ubiqué la etiqueta body y en ella asigne la seccion header 
en el header agregué estilo mediante un selector de id y modifique el tamaño de la imagen que se encuentra alli mediante un selector de tipo, configure la margen y el color de fondo.
 luego asigné otra seccion main y a article, en ella introduje una seccion la cual tiene un formato que aplique a la tabla, main le puse selector de clase, para configurar el contenido le coloque la propiedad flex box para poder alinear tanto horizontal como verticalmente.
 a su ves una seccion article,  y dentro de esta una etiqueta de estructura llamada “section”, esto para que otros elementos como la tabla, al estar dentro de una sección que es nombrada de la misma manera, tome las mismas propiedades  en la hoja de estilo css.
Cree una tabla , y le dí estilo a la tabla mediante una herramienta (strong) a excepcion de las etiquetas “th” ya que por defecto estas tienen apariencia de “negrita”.
Para la seccion footer, lo primero que hice fue ubicar dos elementos, el elemento article que contiene un texto y el elemento lista en el cual introduje las imágenes, cada una tomada de internet mediante la herramienta img junto con src cabe resaltar que toda imágen tiene la herramienta alt que funciona dandole un texto alternativo, que describe cada imágen.
Al momento de darle estilo a la lista, tuve que quitarle los guiones y a cada elemento de la lista, también utilice elementos de clase para darle estilo tanto a las imágenes como a su contenedor (li).
Por último mencionar que el hover se realizó dandole un estilo con la pseudo etiqueta tipo :hover al elemento img acompañado de un selector de clase , cabe mencionar que le di formato a todo el footer con un color de fondo con una etiqueta de clase.

**Comment by WhitneySt** [comment]
### Calificación
99%
