### ISSUE TITLE
Algoritmo Pseint Sprint 1

### ISSUE THREAD

**Issue by 52364037** [MAKAIABootcamp/frontend-cohorte-4#48]
# Algoritmos Pseint
## Descripcion del desarrollo
Fue creado dede la consola Pseint, aplicando principalmente logica
### Estructuras del proyecto
![image](https://user-images.githubusercontent.com/111030010/222637885-21db03b7-634a-47b9-9c0e-52c2b7a5c8d1.png)
### Resumen del paso a paso
Se descargo la plataforema Pseint y se desarrollaron los ejercicios del workshop 1

**Comment by WhitneySt** [comment]
### Calificación
90%
