### ISSUE TITLE
Whorshop 1. Lógica

### ISSUE THREAD

**Issue by Gesiel19** [MAKAIABootcamp/frontend-cohorte-4#49]
[https://github.com/Gesiel19/sprint_1logica](url)

Este trabajo permite la exploración lógica de ejemplos reales por medio de la herramienta PSeInt.

Estructura de las carpetas.

![Captura de pantalla (186)](https://user-images.githubusercontent.com/125513536/222827813-900922bc-c4fb-4f58-ac06-594deb0c3bee.png)

En función de lo explicado en clases realicé los siguientes ejercicios:

a) Recolección de información para determinar procedimientos.
b) Desarrollo de Algoritmos.
c) <Ejecutar> algoritmos.
d) Guardar cada archivo.

Vista : Desktop
![Captura de pantalla (192)](https://user-images.githubusercontent.com/125513536/222829093-7d0bf9e3-e7d1-43f8-a248-2a3ae527eb1f.png)
![Captura de pantalla (191)](https://user-images.githubusercontent.com/125513536/222829096-3a47366b-af5a-4667-a361-175c06e3a160.png)
![Captura de pantalla (190)](https://user-images.githubusercontent.com/125513536/222829099-875bc5d4-6e0b-4aa1-9a1a-3f6a60a5d21d.png)
![Captura de pantalla (189)](https://user-images.githubusercontent.com/125513536/222829100-b1b8e9ca-dec6-42f0-bbbd-02e7387b83a2.png)
![Captura de pantalla (188)](https://user-images.githubusercontent.com/125513536/222829102-da5dd983-c5dd-44c6-a3db-9c3ee2850f65.png)
![Captura de pantalla (187)](https://user-images.githubusercontent.com/125513536/222829107-39582c25-4aef-4369-a2b8-4a20702c44ba.png)

[https://wakatime.com/dashboard](url) Estadisticas Wakatime

**Comment by WhitneySt** [comment]
### Calificación
94%
