### ISSUE TITLE
Algoritmos Pseint | Workshop1 - Sprint 1

### ISSUE THREAD

**Issue by mario-cartagena** [MAKAIABootcamp/frontend-cohorte-4#5]
# Workshop 1
## Descripción del desarrollo: 
Se realizó el desarrollo de 8 ejercicios de lógica de programación para comprender conceptos y algoritmos en pseudocódigo usando la herramienta PSeint. En cada ejercicio se utilizó cada uno de los conceptos brindados por las docentes.
### Estructura de carpetas:
![image](https://user-images.githubusercontent.com/98544638/222047733-0d48d0e6-561f-43d4-a5f8-dc70e7637389.png)

**Comment by WhitneySt** [comment]
### Calificación
100%
