### ISSUE TITLE
Workshop 2 Pokedex

### ISSUE THREAD

**Issue by 52364037** [MAKAIABootcamp/frontend-cohorte-4#50]
# Workshop 2 Pokedex
### Estructura del proyecto
![image](https://user-images.githubusercontent.com/111030010/222923353-5f2c7a44-7a89-4dd3-9184-f8005f8d42ba.png)
### Resumen del paso a paso y desarrollo
Para la creación de esta pagina, utilice Html (lenguaje de marcado e hipertexto) y CSS (Colección de reglas que afectan a la apariencia de un documento.) y el editor de codigo Visual Studio Code dentro del cual, cree dos archivos: index.html y style.css, Para enlazar el html con el css utilice la linea <link rel="stylesheet" type="text/css" href="style.css" y la estructua basica del HTML y otras etiquetas, tambien descargue imagenes de Google en formato png.
### Vistas
![Captura de pantalla (1)](https://user-images.githubusercontent.com/111030010/222924555-abc1d645-ed19-4f59-94d3-ea2cfe3faa82.png)

## Estadisticas WakaTime
[Estadisticas](https://wakatime.com/@4c058311-0117-4773-b2c9-cd0fd7209568/projects/ekqdukkzhs?start=2023-02-26&end=2023-03-04)

**Comment by WhitneySt** [comment]
### Calificación
95%
