### ISSUE TITLE
pseInt-ejercicios

### ISSUE THREAD

**Issue by vickmery** [MAKAIABootcamp/frontend-cohorte-4#57]
# Algoritmos Pseint

## Descripcion del desarrollo.
Practicas de Algoritmos 

### Estructuras de carpetas:
![image](https://user-images.githubusercontent.com/125513818/223001639-041ebb90-d278-47f6-8185-0f7336b6b9ab.png)

### Resumen de paso a paso y desarrollo.
Realice practicas con Algoritmos solicitados en clase

### Vistas:
![image](https://user-images.githubusercontent.com/125513818/223001724-b0a58885-478d-4e67-a388-c5867733976c.png)

**Comment by vickmery** [comment]
[](url)

**Comment by WhitneySt** [comment]
### Calificación 
86%
