### ISSUE TITLE
Pokedex | Workshop 2 - Sprint 1 

### ISSUE THREAD

**Issue by mario-cartagena** [MAKAIABootcamp/frontend-cohorte-4#8]
# Workshop 2
## Descripción del desarrollo: 
Se realizó la construcción de una página web estática usando HTML y CSS siguiendo la estructura dada:
![image](https://user-images.githubusercontent.com/98544638/222187857-3dcac6d6-a90c-464c-9edd-4e0ef541874f.png)
### Estructura de carpetas:
La estructuración está basada en dos carpetas principales y un archivo *index.html*, en la primer carpeta (*css*) se encuentra el archivo *style.css* que contiene todos los estilos aplicados al workshop y en la segunda carpeta (*img*) se encuentran las imagenes utilizadas para el header y una sección del main. Las imagenes de los pokemones se sacaron de la PokeApi Oficial. El archivo *index.html* contiene toda la estructura requerida del workshop.

![image](https://user-images.githubusercontent.com/98544638/222188556-0195a192-181f-4bb4-9ff2-04d88fee1aa0.png)
### Resumen paso a paso:
En el workshop se tuvieron en cuenta los requerimientos dados para el desarrollo correcto de la página web estática, contando con la estructuración requerida (header, main y footer) y el uso de la pseudo-clase :hover para visualizar el efecto del mouse cuando el usuario esté interactuando con los pokemones del footer.

**1.**  Se construye la estructuración de la página web estática en el archivo *index.html* respetando el contenido dado: header, main y footer, además usando lenguaje HTML con sus etiquetas semánticas: section, article, figure y demás. Solo se utilizó una etiqueta *div* para el nombre y el ícono de fuego del Pokémon "Charizard".
 
![code](https://user-images.githubusercontent.com/98544638/222200794-1d28dc12-0555-4c48-ae14-a735f77fcf23.png)

**2.**  Para las imágenes de los Pokémon se utilizó el sitio web [PokeAPI](https://pokeapi.co/), el cual nos permite buscar todas las propiedades de los distintos Pokémon, entre esas su imagen oficial en formato *.png*.

![image](https://user-images.githubusercontent.com/98544638/222202159-c100bee7-555a-4cbd-8d98-b91313f02700.png)

**3.** Para finalizar se aplicaron los estilos suficientes para que la página fuera lo más parecido posible. Dichos estilos se encuentran en el archivo *style.css*.

#### Vista Desktop:
![chrome-capture-2023-2-1](https://user-images.githubusercontent.com/98544638/222204620-4e0ab784-4f86-415d-bcca-1c63e6d0edf2.png)

### Vista Desktop con hover:
![image](https://user-images.githubusercontent.com/98544638/222204877-c68e5f6a-fe7c-4124-af00-a81a287543c2.png)
 
### Estadísticas Wakatime: 
Se adjuntan dos estadísticas debido a que cambié el nombre de la carpeta a último momento, pero en las dos se trabajó en el Workshop 2. 

[Estadística](https://wakatime.com/@5fc61b94-21cb-4f47-89df-c8c38183b231/projects/qkrjnwbdry?start=2023-02-23&end=2023-03-01)
![image](https://user-images.githubusercontent.com/98544638/222205585-3337f59b-6a26-483a-9910-ba0f8a2b028a.png)

[Estadística](https://wakatime.com/@5fc61b94-21cb-4f47-89df-c8c38183b231/projects/sfuhpirubm?start=2023-02-23&end=2023-03-01)
![image](https://user-images.githubusercontent.com/98544638/222205682-c5c99c98-ad32-4a27-9944-1e78934064af.png)

**Comment by WhitneySt** [comment]
### Calificación
100%
