### ISSUE TITLE
Sprint 1 |  Workshop 1 | Pseint 

### ISSUE THREAD

**Issue by NeisRosado** [MAKAIABootcamp/frontend-cohorte-4#9]
# Algoritmos Pseint 

## Descripción del Desarrollo 
En este Workshop se resolvieron algoritmos en pseudocódigo empleando la herramienta Pseint. 
 ### Estructura de Carpetas 

![pseintimg](https://user-images.githubusercontent.com/125513445/222225583-efaf7b83-3a72-4af6-8f80-11a2edc50b55.PNG)

### Resumen Paso a Paso

Para resolver los ejercicios fue necesario: 
 - Analizar las descripciones de los ejercicios.
 - Utilizar las fórmulas requeridas para el algoritmo. 

### Vista 

![ejemplopseint](https://user-images.githubusercontent.com/125513445/222228492-0159665f-5a74-400a-a67b-e7797fc302ba.PNG)

**Comment by WhitneySt** [comment]
### Calificación
100%
